use serde::{Deserialize, Serialize};
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};


use crate::monitor::antigravity_discovery::{AntigravityDiscovery, AntigravityRuntime, DiscoveryErrorKind};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum AntigravityRuntimeState {
    AntigravityNotRunning,
    LanguageServerNotFound,
    RpcPortNotFound,
    CsrfTokenNotFound,
    RpcConnectionFailed,
    RpcUnauthorized,
    RpcTimeout,
    InvalidResponse,
    QuotaUnavailable,
    Connected,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AntigravityModelQuota {
    pub model_id: String,
    pub display_name: Option<String>,
    pub remaining_fraction: Option<f64>,
    pub remaining_percent: Option<f64>,
    pub reset_time: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AntigravityQuotaSnapshot {
    pub account_identity: Option<String>,
    pub plan_name: Option<String>,
    pub tier: Option<String>,
    pub models: Vec<AntigravityModelQuota>,
    pub available_prompt_credits: Option<i64>,
    pub available_flow_credits: Option<i64>,
    pub monthly_prompt_credits: Option<i64>,
    pub monthly_flow_credits: Option<i64>,
    pub fetched_at: String,
    pub source: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AntigravityRuntimeDiagnostic {
    pub state: AntigravityRuntimeState,
    pub process_id: Option<u32>,
    pub rpc_host: Option<String>,
    pub rpc_port: Option<u16>,
    pub csrf_token_detected: bool,
    pub http_status: Option<u16>,
    pub model_count: usize,
    pub plan_name: Option<String>,
    pub tier: Option<String>,
    pub latency_ms: Option<u64>,
    pub safe_message: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AntigravityQuotaError {
    pub state: AntigravityRuntimeState,
    pub message: String,
}

impl std::fmt::Display for AntigravityQuotaError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}: {}", self.state, self.message)
    }
}

impl std::error::Error for AntigravityQuotaError {}

pub struct AntigravityQuotaClient {
    http_client: reqwest::Client,
}

impl AntigravityQuotaClient {
    pub fn new() -> Self {
        // Scoped TLS relaxation exclusively for local self-signed cert generated by language_server.exe on 127.0.0.1
        let client = reqwest::Client::builder()
            .danger_accept_invalid_certs(true)
            .timeout(Duration::from_secs(6))
            .build()
            .unwrap_or_else(|_| reqwest::Client::new());

        Self {
            http_client: client,
        }
    }

    /// Fetch real quota and plan status directly from running local Antigravity Language Server
    pub async fn fetch_quota(&self) -> Result<AntigravityQuotaSnapshot, AntigravityQuotaError> {
        let runtime = AntigravityDiscovery::discover_runtime().map_err(|e| {
            let state = match e.kind {
                DiscoveryErrorKind::AntigravityNotRunning => AntigravityRuntimeState::AntigravityNotRunning,
                DiscoveryErrorKind::LanguageServerNotFound => AntigravityRuntimeState::LanguageServerNotFound,
                DiscoveryErrorKind::CsrfTokenNotFound => AntigravityRuntimeState::CsrfTokenNotFound,
                DiscoveryErrorKind::RpcPortNotFound => AntigravityRuntimeState::RpcPortNotFound,
                DiscoveryErrorKind::CommandExecutionFailed => AntigravityRuntimeState::RpcConnectionFailed,
            };
            AntigravityQuotaError {
                state,
                message: e.message,
            }
        })?;

        self.fetch_quota_from_runtime(&runtime).await
    }

    /// Fetch quota from an already discovered runtime
    pub async fn fetch_quota_from_runtime(
        &self,
        runtime: &AntigravityRuntime,
    ) -> Result<AntigravityQuotaSnapshot, AntigravityQuotaError> {
        let url = format!(
            "https://{}:{}/exa.language_server_pb.LanguageServerService/GetUserStatus",
            runtime.rpc_host, runtime.rpc_port
        );

        let resp = self
            .http_client
            .post(&url)
            .header("Content-Type", "application/json")
            .header("Connect-Protocol-Version", "1")
            .header("x-codeium-csrf-token", &runtime.csrf_token)
            .body("{}")
            .send()
            .await
            .map_err(|e| {
                if e.is_timeout() {
                    AntigravityQuotaError {
                        state: AntigravityRuntimeState::RpcTimeout,
                        message: "Connection to Antigravity Language Server timed out.".to_string(),
                    }
                } else {
                    AntigravityQuotaError {
                        state: AntigravityRuntimeState::RpcConnectionFailed,
                        message: format!("Failed to connect to local Antigravity RPC: {}", e),
                    }
                }
            })?;

        let status = resp.status();
        if status.as_u16() == 401 || status.as_u16() == 403 {
            return Err(AntigravityQuotaError {
                state: AntigravityRuntimeState::RpcUnauthorized,
                message: "Antigravity Language Server rejected the local CSRF token.".to_string(),
            });
        }

        if !status.is_success() {
            return Err(AntigravityQuotaError {
                state: AntigravityRuntimeState::InvalidResponse,
                message: format!("Language Server returned HTTP status {}", status),
            });
        }

        let body_text = resp.text().await.map_err(|e| AntigravityQuotaError {
            state: AntigravityRuntimeState::InvalidResponse,
            message: format!("Failed to read Language Server response: {}", e),
        })?;

        let v: serde_json::Value = serde_json::from_str(&body_text).map_err(|e| AntigravityQuotaError {
            state: AntigravityRuntimeState::InvalidResponse,
            message: format!("Failed to parse Language Server JSON: {}", e),
        })?;

        Self::parse_user_status_json(&v)
    }

    /// Run diagnostic check on the local Antigravity runtime
    pub async fn run_diagnostic(&self) -> AntigravityRuntimeDiagnostic {
        let start = Instant::now();

        let runtime = match AntigravityDiscovery::discover_runtime() {
            Ok(r) => r,
            Err(e) => {
                let state = match e.kind {
                    DiscoveryErrorKind::AntigravityNotRunning => AntigravityRuntimeState::AntigravityNotRunning,
                    DiscoveryErrorKind::LanguageServerNotFound => AntigravityRuntimeState::LanguageServerNotFound,
                    DiscoveryErrorKind::CsrfTokenNotFound => AntigravityRuntimeState::CsrfTokenNotFound,
                    DiscoveryErrorKind::RpcPortNotFound => AntigravityRuntimeState::RpcPortNotFound,
                    DiscoveryErrorKind::CommandExecutionFailed => AntigravityRuntimeState::RpcConnectionFailed,
                };
                return AntigravityRuntimeDiagnostic {
                    state,
                    process_id: None,
                    rpc_host: None,
                    rpc_port: None,
                    csrf_token_detected: false,
                    http_status: None,
                    model_count: 0,
                    plan_name: None,
                    tier: None,
                    latency_ms: Some(start.elapsed().as_millis() as u64),
                    safe_message: e.message,
                };
            }
        };

        match self.fetch_quota_from_runtime(&runtime).await {
            Ok(snapshot) => AntigravityRuntimeDiagnostic {
                state: AntigravityRuntimeState::Connected,
                process_id: Some(runtime.process_id),
                rpc_host: Some(runtime.rpc_host),
                rpc_port: Some(runtime.rpc_port),
                csrf_token_detected: !runtime.csrf_token.is_empty(),
                http_status: Some(200),
                model_count: snapshot.models.len(),
                plan_name: snapshot.plan_name,
                tier: snapshot.tier,
                latency_ms: Some(start.elapsed().as_millis() as u64),
                safe_message: format!(
                    "Successfully connected to Antigravity Language Server (PID {} on port {}). Loaded {} live model quotas.",
                    runtime.process_id, runtime.rpc_port, snapshot.models.len()
                ),
            },
            Err(e) => AntigravityRuntimeDiagnostic {
                state: e.state,
                process_id: Some(runtime.process_id),
                rpc_host: Some(runtime.rpc_host),
                rpc_port: Some(runtime.rpc_port),
                csrf_token_detected: !runtime.csrf_token.is_empty(),
                http_status: None,
                model_count: 0,
                plan_name: None,
                tier: None,
                latency_ms: Some(start.elapsed().as_millis() as u64),
                safe_message: e.message,
            },
        }
    }

    /// Parse and normalize `userStatus` response JSON into DCC DTO
    pub fn parse_user_status_json(v: &serde_json::Value) -> Result<AntigravityQuotaSnapshot, AntigravityQuotaError> {
        let user_status = match v.get("userStatus") {
            Some(u) => u,
            None => {
                return Err(AntigravityQuotaError {
                    state: AntigravityRuntimeState::InvalidResponse,
                    message: "Response JSON does not contain 'userStatus' root object.".to_string(),
                });
            }
        };

        let account_identity = user_status.get("email").and_then(|s| s.as_str()).map(|s| s.to_string());

        let plan_status = user_status.get("planStatus");
        let plan_info = plan_status.and_then(|p| p.get("planInfo"));

        let plan_name = plan_info
            .and_then(|pi| pi.get("planName"))
            .and_then(|s| s.as_str())
            .map(|s| s.to_string());

        let tier = plan_info
            .and_then(|pi| pi.get("teamsTier"))
            .and_then(|s| s.as_str())
            .map(|s| s.to_string());

        let available_prompt_credits = plan_status
            .and_then(|p| p.get("availablePromptCredits"))
            .and_then(|c| c.as_i64());

        let available_flow_credits = plan_status
            .and_then(|p| p.get("availableFlowCredits"))
            .and_then(|c| c.as_i64());

        let monthly_prompt_credits = plan_info
            .and_then(|pi| pi.get("monthlyPromptCredits"))
            .and_then(|c| c.as_i64());

        let monthly_flow_credits = plan_info
            .and_then(|pi| pi.get("monthlyFlowCredits"))
            .and_then(|c| c.as_i64());

        let mut models = Vec::new();
        if let Some(model_configs) = user_status
            .get("cascadeModelConfigData")
            .and_then(|c| c.get("clientModelConfigs"))
            .and_then(|m| m.as_array())
        {
            for m in model_configs {
                let display_name = m.get("label").and_then(|s| s.as_str()).map(|s| s.to_string());
                let model_id = m
                    .get("modelOrAlias")
                    .and_then(|moa| moa.get("model"))
                    .and_then(|s| s.as_str())
                    .unwrap_or("unknown")
                    .to_string();

                let quota_info = m.get("quotaInfo");
                let remaining_fraction = quota_info.and_then(|q| q.get("remainingFraction")).and_then(|f| f.as_f64());
                let remaining_percent = remaining_fraction.map(|f| f * 100.0);
                let reset_time = quota_info.and_then(|q| q.get("resetTime")).and_then(|s| s.as_str()).map(|s| s.to_string());

                models.push(AntigravityModelQuota {
                    model_id,
                    display_name,
                    remaining_fraction,
                    remaining_percent,
                    reset_time,
                });
            }
        }

        let fetched_at = current_unix_timestamp().to_string();

        Ok(AntigravityQuotaSnapshot {
            account_identity,
            plan_name,
            tier,
            models,
            available_prompt_credits,
            available_flow_credits,
            monthly_prompt_credits,
            monthly_flow_credits,
            fetched_at,
            source: "AntigravityLocalRuntime".to_string(),
        })
    }
}

fn current_unix_timestamp() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_user_status_normalization() {
        let json_data = serde_json::json!({
            "userStatus": {
                "email": "developer@example.com",
                "planStatus": {
                    "planInfo": {
                        "planName": "Pro",
                        "teamsTier": "TEAMS_TIER_PRO",
                        "monthlyPromptCredits": 50000,
                        "monthlyFlowCredits": 150000
                    },
                    "availablePromptCredits": 500,
                    "availableFlowCredits": 120000
                },
                "cascadeModelConfigData": {
                    "clientModelConfigs": [
                        {
                            "label": "Gemini 3.7 Flash (High)",
                            "modelOrAlias": {
                                "model": "MODEL_PLACEHOLDER_M298"
                            },
                            "quotaInfo": {
                                "remainingFraction": 0.6648536,
                                "resetTime": "2026-08-16T06:27:27Z"
                            }
                        },
                        {
                            "label": "Claude Sonnet 4.6 (Thinking)",
                            "modelOrAlias": {
                                "model": "MODEL_PLACEHOLDER_M35"
                            },
                            "quotaInfo": {
                                "remainingFraction": 1.0,
                                "resetTime": "2026-08-16T07:23:59Z"
                            }
                        }
                    ]
                }
            }
        });

        let snapshot = AntigravityQuotaClient::parse_user_status_json(&json_data).unwrap();
        assert_eq!(snapshot.account_identity, Some("developer@example.com".to_string()));
        assert_eq!(snapshot.plan_name, Some("Pro".to_string()));
        assert_eq!(snapshot.tier, Some("TEAMS_TIER_PRO".to_string()));
        assert_eq!(snapshot.available_prompt_credits, Some(500));
        assert_eq!(snapshot.models.len(), 2);

        let m1 = &snapshot.models[0];
        assert_eq!(m1.display_name, Some("Gemini 3.7 Flash (High)".to_string()));
        assert_eq!(m1.model_id, "MODEL_PLACEHOLDER_M298");
        assert_eq!(m1.remaining_fraction, Some(0.6648536));
        assert_eq!(m1.remaining_percent, Some(66.48536));
        assert_eq!(m1.reset_time, Some("2026-08-16T06:27:27Z".to_string()));

        let m2 = &snapshot.models[1];
        assert_eq!(m2.display_name, Some("Claude Sonnet 4.6 (Thinking)".to_string()));
        assert_eq!(m2.remaining_fraction, Some(1.0));
        assert_eq!(m2.remaining_percent, Some(100.0));
    }

    #[test]
    fn test_missing_fields_graceful_handling() {
        let json_minimal = serde_json::json!({
            "userStatus": {}
        });

        let snapshot = AntigravityQuotaClient::parse_user_status_json(&json_minimal).unwrap();
        assert_eq!(snapshot.models.len(), 0);
        assert_eq!(snapshot.plan_name, None);
        assert_eq!(snapshot.tier, None);
    }
}
